version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: KeyPortal-Postgresql
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=keyportal

volumes:
  db-data: