FROM registry.access.redhat.com/ubi9/ubi:9.2

RUN dnf install -y openssh-clients && dnf clean all

RUN useradd -u 1001 -r -g root -d /work -s /sbin/nologin quarkus

WORKDIR /work/
COPY --chown=1001:root --chmod=0755 target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
